- hosts: localhost
  gather_facts: false
  tasks:
    - name: "Ensure bucket exists"
      mjlshen.google_storage_bucket.google_storage_bucket:
        name: "{{ gcp_bucket_name }}"
        project: "{{ gcp_project }}"
        storage_class: "STANDARD"
        location: "us-central1"
        versioning_enabled: true
        labels:
          first: "label"
          second: "label2"
        state: absent
      register: test
